"""Generate BIR report PDFs and CSV exports."""

import csv
import io
import os
from typing import Any

from jinja2 import Template
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

from backend.config import settings


def generate_pdf_report(report_type: str, data: dict[str, Any], tenant_info: dict) -> str:
    """Generate a PDF report and return the file path."""
    filename = f"{report_type}_{data.get('period', 'unknown')}_{tenant_info.get('tin', 'no_tin')}.pdf"
    filepath = os.path.join(settings.report_dir, filename)

    if report_type == "BIR_2550M":
        _generate_bir_2550m_pdf(filepath, data, tenant_info)
    else:
        _generate_generic_pdf(filepath, report_type, data, tenant_info)

    return filepath


def _generate_bir_2550m_pdf(filepath: str, data: dict, tenant_info: dict) -> None:
    """Generate BIR 2550M Monthly VAT Declaration PDF."""
    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter

    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width / 2, height - 50, "BIR Form 2550M")
    c.setFont("Helvetica", 10)
    c.drawCentredString(width / 2, height - 65, "Monthly Value-Added Tax Declaration")

    # Company info
    y = height - 100
    c.setFont("Helvetica-Bold", 10)
    c.drawString(72, y, "Taxpayer Information")
    y -= 20
    c.setFont("Helvetica", 9)

    info_fields = [
        ("Company Name", tenant_info.get("company_name", "")),
        ("TIN", tenant_info.get("tin_number", "")),
        ("RDO Code", tenant_info.get("rdo_code", "")),
        ("Period", data.get("period", "")),
    ]
    for label, value in info_fields:
        c.drawString(72, y, f"{label}: {value}")
        y -= 15

    # Sales section
    y -= 20
    c.setFont("Helvetica-Bold", 10)
    c.drawString(72, y, "Part I - Sales/Receipts")
    y -= 20
    c.setFont("Helvetica", 9)

    sales_fields = [
        ("Vatable Sales", data.get("vatable_sales", "0")),
        ("VAT-Exempt Sales", data.get("vat_exempt_sales", "0")),
        ("Zero-Rated Sales", data.get("zero_rated_sales", "0")),
        ("Total Sales", data.get("total_sales", "0")),
        ("Output VAT (12%)", data.get("output_vat", "0")),
    ]
    for label, value in sales_fields:
        c.drawString(90, y, label)
        c.drawRightString(width - 72, y, f"PHP {_format_amount(value)}")
        y -= 15

    # Input VAT section
    y -= 15
    c.setFont("Helvetica-Bold", 10)
    c.drawString(72, y, "Part II - Input VAT")
    y -= 20
    c.setFont("Helvetica", 9)

    input_fields = [
        ("Input VAT on Goods", data.get("input_vat_goods", "0")),
        ("Input VAT on Services", data.get("input_vat_services", "0")),
        ("Input VAT on Capital Goods", data.get("input_vat_capital", "0")),
        ("Total Input VAT", data.get("total_input_vat", "0")),
    ]
    for label, value in input_fields:
        c.drawString(90, y, label)
        c.drawRightString(width - 72, y, f"PHP {_format_amount(value)}")
        y -= 15

    # Summary
    y -= 15
    c.setFont("Helvetica-Bold", 10)
    c.drawString(72, y, "Part III - Tax Due")
    y -= 20
    c.setFont("Helvetica", 9)

    summary_fields = [
        ("VAT Payable", data.get("vat_payable", "0")),
        ("Tax Credit Carried Forward", data.get("tax_credit_carried_forward", "0")),
    ]
    for label, value in summary_fields:
        c.drawString(90, y, label)
        c.drawRightString(width - 72, y, f"PHP {_format_amount(value)}")
        y -= 15

    y -= 5
    c.setFont("Helvetica-Bold", 11)
    c.drawString(90, y, "NET VAT PAYABLE")
    c.drawRightString(width - 72, y, f"PHP {_format_amount(data.get('net_vat_payable', '0'))}")

    # Footer
    c.setFont("Helvetica", 7)
    c.drawCentredString(width / 2, 40, "Generated by AIStarlight - AI Tax Filing Assistant")

    c.save()


def _generate_generic_pdf(filepath: str, report_type: str, data: dict, tenant_info: dict) -> None:
    """Generic PDF generator for future report types."""
    c = canvas.Canvas(filepath, pagesize=letter)
    width, height = letter

    c.setFont("Helvetica-Bold", 16)
    c.drawCentredString(width / 2, height - 50, f"BIR Form {report_type.replace('BIR_', '')}")

    y = height - 100
    c.setFont("Helvetica", 10)
    c.drawString(72, y, f"Company: {tenant_info.get('company_name', '')}")
    y -= 15
    c.drawString(72, y, f"TIN: {tenant_info.get('tin_number', '')}")
    y -= 30

    for key, value in data.items():
        c.drawString(72, y, f"{key}: {value}")
        y -= 15
        if y < 72:
            c.showPage()
            y = height - 72

    c.save()


def generate_csv_export(data: dict[str, Any]) -> str:
    """Generate CSV string from report data."""
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["Field", "Value"])
    for key, value in data.items():
        writer.writerow([key, value])
    return output.getvalue()


def _format_amount(value: str) -> str:
    """Format a numeric string as currency."""
    try:
        num = float(value)
        return f"{num:,.2f}"
    except (ValueError, TypeError):
        return value
